 Scientific Individual Project:
A Dashboard for Evolving Variability in Configurable System Software

6CP (180h)
12 weeks = ~15 hours/week

Grading (33% Implementation + 66% Scientific Contribution):
- 33% Implementation, 33% Documentation, and 33% Presentation or
- 33% Implementation, 66% Presentation

Documentation/Presentation: Should be scientifically oriented, including motivation, background, related work, implementation, demo, and discussion (prepare early as it has big impact on grade).

* Supported Metrics

- source lines of code
- number of features
- number of configurations
- time needed to compute number of features
- time needed to compute number of configurations

* User Stories

** High Priority

- Users can switch easily between several KConfig-based projects like the Linux kernel, BusyBox, etc. (similar to elixir.bootlin.com).
- Users can view the most recent value of the supported metrics.
- Users can view how the metrics have changed in the last week, month, and year.(dashboard: +X zu letzter woche, +Y zu letztem monat etc)
- Users can view all metric values for a specified revision of a given project.
- For Linux, users can choose either a specific architecture or an aggregation for the whole kernel.
- Users can inspect the evolution history of all metrics in a graph. 

** Nice to Have

- The solution can easily be extended to add more metrics.
- The solution allows for future projection.

* Scientific Contribution

- Provides quick access to empirical facts about configurable system-software projects, which are currently either unknown, inaccurate, or scattered across the literature.
- Extends our TOSEM submission with new data for other projects than the Linux kernel, so we can check whether our conclusions also apply to other projects.

* Technical Contribution

- Frontend development based on existing evaluation data provided with torte.
- Challenge: How to correctly incorporate complex calculations (from Python) for the number of features and configurations?
- Implementation of backend e.g. with Express.js, frontend with the Astro framework, visualization with Plotly and, potentially, its HTML export.
